services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    hostname: spark
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "10010:8080"
      - "7077:7077"
    working_dir: /spark
    volumes:
      - .:/spark
    networks:
      - dibimbing

  spark-worker-1:
    image: bitnami/spark:latest
    container_name: spark-worker-1
    ports:
      - "10011:8081"
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    working_dir: /spark
    volumes:
      - .:/spark
    networks:
      - dibimbing

  spark-worker-2:
    image: bitnami/spark:latest
    container_name: spark-worker-2
    ports:
      - "10012:8081"
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    working_dir: /spark
    volumes:
      - .:/spark
    networks:
      - dibimbing

networks:
  dibimbing:
    external: true